services:

  estate-ui:
    build: ./estate-ui
    container_name: estate-ui
    networks:
      - homelab-net

  lab-mysql:
    image: mysql:8
    container_name: lab-mysql
    environment:
      MYSQL_ROOT_PASSWORD: labpass
      MYSQL_DATABASE: homelab
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - homelab-net

  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - homelab-net

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - homelab-net

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks:
      - homelab-net

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - homelab-net

  proxy:
    image: nginx
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - estate-ui
    networks:
      - homelab-net

volumes:
  mysql_data:
  portainer_data:

networks:
  homelab-net:
    driver: bridge
